server:
  port: 5000
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/CS211180?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8
    username: root
    password: 52780
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
    default-property-inclusion: ALWAYS
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB